version: "3.9"

services:

  consumer:
    build:
      args:
        USER: ${USER:-nextjs}
      context: ./
      dockerfile: ${SERVICE_DOCKER_FILE:-docker/test.Dockerfile}
    volumes:
      - ./__tests__:/app/__tests__:ro
      - ./declarations:/app/declarations:ro
      - ./public:/app/public:ro
      - ./src:/app/src:ro
    user: ${USER:-nextjs}
